# GitHub Actions专用的简化wrangler配置
# 只包含核心功能，确保部署成功

name = "destiny-backend"
main = "worker.ts"
compatibility_date = "2024-08-01"

# 基本环境变量配置
[vars]
NODE_ENV = "production"
CORS_ORIGIN = "https://destiny-frontend.pages.dev"
FRONTEND_URL = "https://destiny-frontend.pages.dev"
DEEPSEEK_BASE_URL = "https://api.deepseek.com/v1/chat/completions"
DEEPSEEK_MODEL = "deepseek-chat"
EMAIL_SERVICE = "resend"
RESEND_FROM_EMAIL = "info@info.indicate.top"
RESEND_FROM_NAME = "indicate.top"

# D1数据库绑定 - 核心功能
[[d1_databases]]
binding = "DB"
database_name = "destiny-db"
database_id = "500716dc-3ac2-4b4a-a2ee-ad79b301228d"

# 注意：敏感环境变量通过GitHub Secrets和wrangler secret设置：
# - CLOUDFLARE_API_TOKEN (GitHub Secret)
# - CLOUDFLARE_ACCOUNT_ID (GitHub Secret)
# - JWT_SECRET (wrangler secret)
# - DEEPSEEK_API_KEY (wrangler secret)
# - RESEND_API_KEY (wrangler secret)
# - STRIPE_SECRET_KEY (wrangler secret)
# - STRIPE_WEBHOOK_SECRET (wrangler secret)
