name = "destiny-backend"
main = "worker.js"
compatibility_date = "2024-08-01"

[env.production]
name = "destiny-backend-prod"

# D1 数据库配置
[[d1_databases]]
binding = "DB"
database_name = "destiny-db"
database_id = "500716dc-3ac2-4b4a-a2ee-ad79b301228d"

# 环境变量（在Cloudflare Dashboard中配置）
[vars]
NODE_ENV = "production"
JWT_SECRET = "destiny-super-secret-jwt-key-for-production"
DEEPSEEK_API_KEY = "sk-nnbbhnefkzmdawkfohjsqtqdeelbygvrihbafpppupvfpfxn"
DEEPSEEK_BASE_URL = "https://api.siliconflow.cn/v1/chat/completions"
DEEPSEEK_MODEL = "Pro/deepseek-ai/DeepSeek-R1"
RESEND_API_KEY = "re_DsCfph4T_PPAMJQnhoSiAv3AjYUy5f9HP"
RESEND_FROM_EMAIL = "info@info.indicate.top"
RESEND_FROM_NAME = "Indicate.Top"
EMAIL_SERVICE = "resend"
FRONTEND_URL = "https://d576ae7f.destiny-frontend.pages.dev"
CORS_ORIGIN = "https://d576ae7f.destiny-frontend.pages.dev"
