# Wrangler 配置文件 - 最终生产版 V4
# 这是一个用于生产部署的、最简化的配置。
# 它不包含任何环境（[env]），以避免在CI/CD中产生混淆。
# 环境变量将完全通过Cloudflare UI进行管理。

name = "destiny-backend"
main = "worker.ts"
compatibility_date = "2024-08-01"

# 移除可能导致部署问题的配置
# [build] 和 [limits] 配置可能在某些环境下导致问题
# 如果需要这些配置，可以在部署成功后再添加

# D1数据库绑定
# 这是唯一的数据库配置，将用于所有部署。
[[d1_databases]]
binding = "DB"
database_name = "destiny-db"
database_id = "500716dc-3ac2-4b4a-a2ee-ad79b301228d"

# Cloudflare Queues配置 - AI异步处理队列
[[queues.producers]]
binding = "AI_QUEUE"
queue = "ai-processing-queue"

[[queues.consumers]]
queue = "ai-processing-queue"
max_batch_size = 1
max_batch_timeout = 30
max_retries = 2
dead_letter_queue = "ai-processing-dlq"

# 死信队列配置
[[queues.producers]]
binding = "AI_DLQ"
queue = "ai-processing-dlq"

# 定时任务配置 - 每2分钟自动处理卡住的任务（在前端超时前及时恢复）
[triggers]
crons = ["*/2 * * * *"]

