# CI/CD友好的wrangler配置
name = "destiny-backend"
main = "worker.ts"
compatibility_date = "2024-08-01"

# 基本环境变量
[vars]
NODE_ENV = "production"
CORS_ORIGIN = "https://destiny-frontend.pages.dev"
FRONTEND_URL = "https://destiny-frontend.pages.dev"

# D1数据库绑定
[[d1_databases]]
binding = "DB"
database_name = "destiny-db"
database_id = "your-database-id"

# 注意：敏感环境变量通过wrangler secret设置
# STRIPE_SECRET_KEY (通过 wrangler secret put STRIPE_SECRET_KEY)
# STRIPE_WEBHOOK_SECRET (通过 wrangler secret put STRIPE_WEBHOOK_SECRET)
