# Wrangler 配置文件 - 最终生产版 V4
# 这是一个用于生产部署的、最简化的配置。
# 它不包含任何环境（[env]），以避免在CI/CD中产生混淆。
# 环境变量将完全通过Cloudflare UI进行管理。

name = "destiny-backend"
main = "worker.ts"
compatibility_date = "2024-08-01"

# Cloudflare Worker限制配置
# 注意：这些限制需要付费计划才能生效
# 免费计划有固定的30秒CPU时间限制
[limits]
cpu_ms = 300000

# 兼容性标志，启用更长的执行时间支持
compatibility_flags = ["nodejs_compat"]

# D1数据库绑定
# 这是唯一的数据库配置，将用于所有部署。
[[d1_databases]]
binding = "DB"
database_name = "destiny-db"
database_id = "500716dc-3ac2-4b4a-a2ee-ad79b301228d"

