# 默认配置（适用于所有环境，除非被覆盖）
name = "destiny-backend"
main = "worker.ts"
compatibility_date = "2024-08-01"

# 新增：定义文本模块规则，以允许直接导入.sql文件
[[rules]]
type = "Text"
globs = ["**/*.sql"]

# 开发环境配置
[dev]
# 开发时使用的D1数据库
[[d1_databases]]
binding = "DB"
database_name = "destiny-db-dev"
database_id = "500716dc-3ac2-4b4a-a2ee-ad79b301228d"

# 生产环境配置
[env.production]
# 生产环境使用的D1数据库
[[d1_databases]]
binding = "DB"
database_name = "destiny-db-prod"
database_id = "500716dc-3ac2-4b4a-a2ee-ad79b301228d"

# 生产环境变量将通过Cloudflare仪表盘设置
# [env.production.vars]
# NODE_ENV = "production"
# ...

